### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by o1066** [libhazeltine/libhazeltine#11]
Unsure if this repo still takes suggestions.
Not necessarily 100% about psionics, though it some has interesting information and resources
https://web.archive.org/web/20210226132959/https://www.noein.co/

**Comment by libhazeltine** [comment]
I have spoken in the past with the person who ran Noein, and it is my understanding that they have an active disinterest in being associated with the OEC. I have already [removed](https://github.com/libhazeltine/libhazeltine/commit/a7014c433baa6d575e89db4e36d4b5b9c7f36c9a) another site they operated from the index upon learning that they ran it.
